DROP TABLE IF EXISTS vcdb_incidents;
CREATE TABLE vcdb_incidents (
  "incident_id" TEXT,
  "summary" TEXT,
  "plus.created" TEXT,
  "plus.modified" TEXT,
  "impact.notes" TEXT,
  "victim.victim_id" TEXT,
  "victim.industry" TEXT,
  "plus.timeline.notification.year" FLOAT,
  "plus.timeline.notification.month" FLOAT,
  "timeline.discovery.value" FLOAT,
  "action.Malware" BOOLEAN,
  "action.Hacking" BOOLEAN,
  "action.Social" BOOLEAN,
  "action.Physical" BOOLEAN,
  "action.Misuse" BOOLEAN,
  "action.Error" BOOLEAN,
  "action.Environmental" BOOLEAN,
  "action.Unknown" BOOLEAN,
  "actor.External" BOOLEAN,
  "actor.Internal" BOOLEAN,
  "actor.Partner" BOOLEAN,
  "actor.Unknown" BOOLEAN,
  "attribute.Confidentiality" BOOLEAN,
  "attribute.Integrity" BOOLEAN,
  "attribute.Availability" BOOLEAN,
  "asset_assets_variety" TEXT,
  "asset_assets_amount" FLOAT,
  "asset_assets_value" TEXT,
  "asset_cloud" TEXT
);
